Repository FabricMC/Enigma, pull requests merged in 2021-07, with the labels that each got.

#414 Update cfr and fixes a few related issues
  enigma/build.gradle
  enigma/src/main/java/cuchaz/enigma/source/cfr/CfrDecompiler.java
  enigma/src/main/java/cuchaz/enigma/source/cfr/CfrSource.java
  enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
Labels: bug, cfr

#418 Update proguard
  enigma/build.gradle
Labels: enhancement

#409 Makes sure save mappings is completed before next action
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
Labels: bug, interface

#406 Add --single-class-tree argument that puts all classes into deobf panel & hides obf panel
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/DeobfPanel.java
  enigma/src/main/resources/lang/en_us.json
Labels: enhancement, interface

#364 Entry Changes
  enigma-server/docs/protocol.md
  enigma-server/src/main/java/cuchaz/enigma/network/ClientPacketHandler.java
  enigma-server/src/main/java/cuchaz/enigma/network/EnigmaServer.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/ChangeDocsC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/ChangeDocsS2CPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/EntryChangeC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/EntryChangeS2CPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/MarkDeobfuscatedC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/MarkDeobfuscatedS2CPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/PacketHelper.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/PacketRegistry.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/RemoveMappingC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/RemoveMappingS2CPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/RenameC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/RenameS2CPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/SyncMappingsS2CPacket.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/newabstraction/EntryValidation.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/DeobfPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/ObfPanel.java
  enigma/src/main/java/cuchaz/enigma/source/DecompiledClassSource.java
  enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
  enigma/src/main/java/cuchaz/enigma/source/procyon/transformers/AddJavadocsAstTransform.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryChange.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryMapping.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryUtil.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingsChecker.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/RawEntryMapping.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tiny/TinyMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Writer.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/tree/HashEntryTree.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/Lambda.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassDefEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/Entry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldDefEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/LocalVariableDefEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/LocalVariableEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodDefEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodEntry.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ParentedEntry.java
  enigma/src/main/java/cuchaz/enigma/utils/TristateChange.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/PrintValidatable.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ValidationContext.java
  enigma/src/test/java/cuchaz/enigma/translation/mapping/TestReadWriteCycle.java
Labels: mapping, optimization
