Repository FabricMC/Enigma, pull requests merged in 2021-05, with the labels that each got.

#389 Bump cfr and gradle wrapper
  enigma/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#381 Add EnigmaMappingsReader.readFiles
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
Labels: enhancement, mapping

#390 Update to Java 16
  .github/workflows/build.yml
  .github/workflows/release.yml
  build.gradle
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/legacy/Config.java
  enigma/build.gradle
  enigma/src/test/java/cuchaz/enigma/TestDeobfed.java
  enigma/src/test/java/cuchaz/enigma/TestDeobfuscator.java
  enigma/src/test/java/cuchaz/enigma/TestTokensConstructors.java
  enigma/src/test/java/cuchaz/enigma/TokenChecker.java
Labels: enhancement

#394 Cleanup with Java 16
  enigma-server/src/main/java/cuchaz/enigma/network/packet/ChangeDocsC2SPacket.java
  enigma-server/src/main/java/cuchaz/enigma/network/packet/SyncMappingsS2CPacket.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/config/LookAndFeel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/FontDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/panels/StructurePanel.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/CallsTreeCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/ImplementationsTreeCellRenderer.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/InheritanceTreeCellRenderer.java
  enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
  enigma/src/main/java/cuchaz/enigma/analysis/ClassReferenceTreeNode.java
  enigma/src/main/java/cuchaz/enigma/analysis/EntryReference.java
  enigma/src/main/java/cuchaz/enigma/analysis/FieldReferenceTreeNode.java
  enigma/src/main/java/cuchaz/enigma/analysis/InterpreterPair.java
  enigma/src/main/java/cuchaz/enigma/analysis/MethodReferenceTreeNode.java
  enigma/src/main/java/cuchaz/enigma/analysis/StructureTreeNode.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/EntryIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/IndexReferenceVisitor.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
  enigma/src/main/java/cuchaz/enigma/classprovider/ObfuscationFixClassProvider.java
  enigma/src/main/java/cuchaz/enigma/source/SourceIndex.java
  enigma/src/main/java/cuchaz/enigma/translation/Translator.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/AccessModifier.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryResolver.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/IdentifierValidation.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/IndexEntryResolver.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingsChecker.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/srg/SrgMappingsWriter.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Writer.java
  enigma/src/main/java/cuchaz/enigma/translation/mapping/tree/EntryTreeNode.java
  enigma/src/main/java/cuchaz/enigma/utils/I18n.java
  enigma/src/main/java/cuchaz/enigma/utils/Utils.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/ParameterizedMessage.java
  enigma/src/main/java/cuchaz/enigma/utils/validation/PrintValidatable.java
Labels: misc, optimization
