Repository FabricMC/Enigma, pull requests merged in 2023-09, with the labels that each got.

#531 Index more class references
  enigma/src/main/java/cuchaz/enigma/analysis/index/IndexReferenceVisitor.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndexer.java
  enigma/src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
  enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
Labels: enhancement, analysis

#530 Fix documenting constructors (again)
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
Labels: bug

#529 Search dialog improvements
  enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
  enigma-swing/src/main/java/cuchaz/enigma/gui/search/SearchUtil.java
  enigma/src/main/resources/lang/en_us.json
Labels: interface
